name: mpc_mobile_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  coolicons: ^1.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  dio: ^5.8.0+1
  url_launcher: ^6.3.1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - "assets/logo.png"
    - 'assets/'

  fonts:
    - family: "GoodTimes"
      fonts:
        - asset: "assets/fonts/GoodTimes.otf"
    - family: "SF-Pro"
      fonts:
        - asset: "assets/fonts/SF_pro/SF-Pro-Display-Regular.otf"
          weight: 400
        - asset: "assets/fonts/SF_pro/SF-Pro-Display-Medium.otf"
          weight: 500
        - asset: "assets/fonts/SF_pro/SF-Pro-Display-Semibold.otf"
          weight: 600
        - asset: "assets/fonts/SF_pro/SF-Pro-Display-Bold.otf"
          weight: 700
