// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzkRJgNcGXlnZ3Iw-rtOiSgq86pq6Cyks',
    appId: '1:408557830192:web:aab347942ba9b5e141edf5',
    messagingSenderId: '408557830192',
    projectId: 'midlands-perfomance-club',
    authDomain: 'midlands-perfomance-club.firebaseapp.com',
    storageBucket: 'midlands-perfomance-club.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNryBLvh3VaBuO9x9BGPux4kJqtOMCJtc',
    appId: '1:408557830192:android:33120ce233d98c9141edf5',
    messagingSenderId: '408557830192',
    projectId: 'midlands-perfomance-club',
    storageBucket: 'midlands-perfomance-club.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFgKgoBBFnrvx8iIAWF6BTfsRw5JKy1RM',
    appId: '1:408557830192:ios:39238aeccb1e097541edf5',
    messagingSenderId: '408557830192',
    projectId: 'midlands-perfomance-club',
    storageBucket: 'midlands-perfomance-club.firebasestorage.app',
    iosBundleId: 'com.example.mpcMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFgKgoBBFnrvx8iIAWF6BTfsRw5JKy1RM',
    appId: '1:408557830192:ios:39238aeccb1e097541edf5',
    messagingSenderId: '408557830192',
    projectId: 'midlands-perfomance-club',
    storageBucket: 'midlands-perfomance-club.firebasestorage.app',
    iosBundleId: 'com.example.mpcMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzkRJgNcGXlnZ3Iw-rtOiSgq86pq6Cyks',
    appId: '1:408557830192:web:ad4464b244e9b23f41edf5',
    messagingSenderId: '408557830192',
    projectId: 'midlands-perfomance-club',
    authDomain: 'midlands-perfomance-club.firebaseapp.com',
    storageBucket: 'midlands-perfomance-club.firebasestorage.app',
  );
}
